[package]
name = "lukas-bot"
version = "0.1.0"
edition = "2021"
publish = false

[lib]

[dependencies]
shuttle-service = { version = "0.11.0", features = ["bot-serenity"] }
anyhow = "1.0.69"
serenity = { version = "0.11.5", default-features = false, features = [
    "client",
    "gateway",
    "rustls_backend",
    "model",
] }
shuttle-secrets = "0.11.0"
shuttle-shared-db = { version = "0.11.0", features = ["postgres"] }
serde = { version = "1.0.155", features = ["derive"] }
tracing = "0.1.37"
sqlx = { version = "0.6.2", features = [
    "runtime-tokio-native-tls",
    "postgres",
] }
